NoDues/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^main/',include('main.urls')),
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^student_profile/$', views.student_profile, name='student_profile'),
    url(r'^rules/$', views.rules, name='rules'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^student_dept_detail/$', views.student_dept_detail, name='student_dept_detail'),
    url(r'^student_lab_detail/$', views.student_lab_detail, name='student_lab_detail'),
    url(r'^caretaker_profile/$', views.caretaker_profile, name='caretaker_profile'),
    url(r'^warden_profile/$', views.warden_profile, name='warden_profile'),
    url(r'^faculty_profile/$', views.faculty_profile, name='faculty_profile'),
    url(r'^gymkhana_profile/$', views.gymkhana_profile, name='gymkhana_profile'),
    url(r'^account_profile/$', views.account_profile, name='account_profile'),
    url(r'^hod_profile/$', views.hod_profile, name='hod_profile'),
    url(r'^cc_profile/$', views.cc_profile, name='cc_profile'),
    url(r'^onlinecc_profile/$', views.onlinecc_profile, name='onlinecc_profile'),
    url(r'^thesis_manager_profile/$', views.thesis_manager_profile, name='thesis_manager_profile'),
    url(r'^library_profile/$', views.library_profile, name='library_profile'),
    url(r'^lab_profile/$', views.lab_profile, name='lab_profile'),
    url(r'^assistant_registrar_profile/$', views.assistant_registrar_profile, name='assistant_registrar_profile'),

]

myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('main.urls',namespace="main")),
]

main/models.py
from django.db import models

# Create your models here.

class Faculty(models.Model):
	name = models.CharField(max_length=250)
	webmail = models.CharField(max_length=100,unique=True)
	password = models.CharField(max_length=250)
	dept = models.CharField(max_length=100)
	#approval = models.BooleanField(default=False)

	def __unicode__(self):
		return self.name

class Lab(models.Model):
	name = models.CharField(max_length=250,default="Lab")
	webmail = models.CharField(max_length=100,unique=True)
	password = models.CharField(max_length=250)

	def __unicode__(self):
		return self.name

class Student(models.Model):
	name = models.CharField(max_length=250)
	roll = models.IntegerField(default=0)
	webmail = models.CharField(max_length=100,unique=True)
	password = models.CharField(max_length=250)
	dept = models.CharField(max_length=100)
	hostel = models.CharField(max_length=100)
	faculty_approval = models.ManyToManyField(Faculty, through = 'StudFacStatus')
	lab_approval = models.ManyToManyField(Lab, through = 'StudLabStatus')
	caretaker_approval = models.BooleanField(default=False)
	warden_approval = models.BooleanField(default=False)
	gymkhana_approval = models.BooleanField(default=False)
	library_approval = models.BooleanField(default=False)
	online_cc_approval = models.BooleanField(default=False)
	cc_approval = models.BooleanField(default=False)
	assistant_registrar_approval = models.BooleanField(default=False)
	submit_thesis = models.BooleanField(default=False)
	hod_approval = models.BooleanField(default=False)
	account_approval = models.BooleanField(default=False)

	def dept_status(self):
		faculty_dept=Faculty.objects.filter(dept=self.dept)
		dept_status =True
		for fac in faculty_dept:
			status = StudFacStatus.objects.get(faculty=fac, student=self).approval
			if status == False:
				dept_status = False
				break
		return dept_status


	def lab_status(self):
		labs=Lab.objects.all()
		lab_status =True
		for lab in labs:
			status = StudLabStatus.objects.get(lab=lab, student=self).approval
			if status == False:
				lab_status = False
				break
		return lab_status

	def __unicode__(self):
		return self.webmail


class StudFacStatus(models.Model):
	faculty = models.ForeignKey(Faculty,on_delete=models.CASCADE)
	student = models.ForeignKey(Student,on_delete=models.CASCADE)
	approval = models.BooleanField(default = False)

	def __unicode__(self):
		return self.student.webmail

class StudLabStatus(models.Model):
	lab = models.ForeignKey(Lab,on_delete=models.CASCADE)
	student = models.ForeignKey(Student,on_delete=models.CASCADE)
	approval = models.BooleanField(default = False)

	def __unicode__(self):
		return self.student.webmail

class Caretaker(models.Model):
	name = models.CharField(max_length=250)
	webmail = models.CharField(max_length=100,unique=True)
	password = models.CharField(max_length=250)
	hostel = models.CharField(max_length=100)

	def __unicode__(self):
		return self.name

class Warden(models.Model):
	name = models.CharField(max_length=250)
	webmail = models.CharField(max_length=100,unique=True)
	password = models.CharField(max_length=250)
	hostel = models.CharField(max_length=100)

	def __unicode__(self):
		return self.name

class Gymkhana(models.Model):
	name = models.CharField(max_length=250,default="Gymkhana")
	webmail = models.CharField(max_length=100,unique=True)
	password = models.CharField(max_length=250)

	def __unicode__(self):
		return self.name

class Library(models.Model):
	name = models.CharField(max_length=250,default="Library")
	webmail = models.CharField(max_length=100,unique=True)
	password = models.CharField(max_length=250)

	def __unicode__(self):
		return self.name

class OnlineCC(models.Model):
	name = models.CharField(max_length=250,default="OnlineCC")
	webmail = models.CharField(max_length=100,unique=True)
	password = models.CharField(max_length=250)

	def __unicode__(self):
		return self.name

class CC(models.Model):
	name = models.CharField(max_length=250,default="CC")
	webmail = models.CharField(max_length=100,unique=True)
	password = models.CharField(max_length=250)

	def __unicode__(self):
		return self.name

class SubmitThesis(models.Model):
	name = models.CharField(max_length=250,default="Submit Thesis")
	webmail = models.CharField(max_length=100,unique=True)
	password = models.CharField(max_length=250)

	def __unicode__(self):
		return self.name

class asstreg(models.Model):
	name = models.CharField(max_length=250)
	webmail = models.CharField(max_length=100,unique=True)
	password = models.CharField(max_length=250)

	def __unicode__(self):
		return self.name

class HOD(models.Model):
	name = models.CharField(max_length=250)
	webmail = models.CharField(max_length=100,unique=True)
	password = models.CharField(max_length=250)
	dept = models.CharField(max_length=100)

	def __unicode__(self):
		return self.name

class Account(models.Model):
	name = models.CharField(max_length=250,default="Account")
	webmail = models.CharField(max_length=100,unique=True)
	password = models.CharField(max_length=250)

	def __unicode__(self):
		return self.name

main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = ['name', 'webmail', 'dept', 'hostel']


class FacultyForm(forms.ModelForm):

    class Meta:
        model = Faculty
        fields = ['webmail', 'dept','name']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

main/views.py
from django.http import HttpResponse
from django.template import loader
from .models import *
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.db.models import Q
from .forms import UserForm




def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        role = request.POST['role']
        # print str(role)
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                role = str(role)
                username=request.user.username
                username = str(username)
                if role == "Student":
                    students = Student.objects.all()
                    
                    flag=0
                    for stud in students:
                        if stud.webmail == username:
                            flag=1
                    if flag==1:
                        return redirect('/student_profile')
                    else:
                        return render(request, 'main/login.html', {'error_message': 'Invalid Role'})

                elif role == "Faculty":
                    faculty = Faculty.objects.all()
                    flag=0
                    for fac in faculty:
                        if fac.webmail == username:
                            flag=1
                    if flag==1:
                        return redirect('/faculty_profile')   
                    else:
                        return render(request, 'main/login.html', {'error_message': 'Invalid Role'})
                    
                elif role == "Lab":
                    labs = Lab.objects.all()
                    flag=0
                    for lab in labs:
                        if lab.webmail == username:
                            flag=1
                    if flag==1:
                        return redirect('/lab_profile')
                    else:
                        return render(request, 'main/login.html', {'error_message': 'Invalid Role'})

                elif role == "Caretaker":
                    caretaker = Caretaker.objects.all()
                    flag=0
                    for care in caretaker:
                        if care.webmail == username:
                            flag=1
                    if flag==1:
                        return redirect('/caretaker_profile')
                    else:
                        return render(request, 'main/login.html', {'error_message': 'Invalid Role'})

                elif role == "Warden":
                    warden = Warden.objects.all()
                    flag=0
                    for ward in warden:
                        if ward.webmail == username:
                            flag=1
                    if flag==1:
                        return redirect('/warden_profile')
                    else:
                        return render(request, 'main/login.html', {'error_message': 'Invalid Role'})

                elif role == "Gymkhana":
                    gymkhana = Gymkhana.objects.all()
                    flag=0
                    for gym in gymkhana:
                        if gym.webmail == username:
                            flag=1
                    if flag==1:
                        return redirect('/gymkhana_profile')
                    else:
                        return render(request, 'main/login.html', {'error_message': 'Invalid Role'})
                   
                elif role == "OnlineCC":
                    onlinecc = OnlineCC.objects.all()
                    flag=0
                    for onl in onlinecc:
                        if onl.webmail == username:
                            flag=1
                    if flag==1:
                        return redirect('/onlinecc_profile')
                    else:
                        return render(request, 'main/login.html', {'error_message': 'Invalid Role'})
                   
                elif role == "CC":
                    cc = CC.objects.all()
                    flag=0
                    for c in cc:
                        if c.webmail == username:
                            flag=1
                    if flag==1:
                        return redirect('cc_profile')
                    else:
                        return render(request, 'main/login.html', {'error_message': 'Invalid Role'})
                   
                elif role == "Thesis Manager":
                    thesis = SubmitThesis.objects.all()
                    flag=0
                    for thes in thesis:
                        if thes.webmail == username:
                            flag=1
                    if flag==1:
                        return redirect('/thesis_manager_profile')
                    else:
                        return render(request, 'main/login.html', {'error_message': 'Invalid Role'})
                    
                elif role == "Library":
                    library = Library.objects.all()
                    flag=0
                    for lib in library:
                        if lib.webmail == username:
                            flag=1
                    if flag==1:
                        return redirect('/library_profile')
                    else:
                        return render(request, 'main/login.html', {'error_message': 'Invalid Role'})
                    
                elif role == "Assistant Registrar":
                    asst = asstreg.objects.all()
                    flag=0
                    for a in asst:
                        if a.webmail == username:
                            flag=1
                    if flag==1:
                        return redirect('/assistant_registrar_profile')
                    else:
                        return render(request, 'main/login.html', {'error_message': 'Invalid Role'})
                    
                elif role == "HOD":
                    hod = HOD.objects.all()
                    flag=0
                    for h in hod:
                        if h.webmail == username:
                            flag=1
                    if flag==1:
                        return redirect('/hod_profile')
                    else:
                        return render(request, 'main/login.html', {'error_message': 'Invalid Role'})
                
                elif role == "Account":
                    account = Account.objects.all()
                    flag=0
                    for acc in account:
                        if acc.webmail == username:
                            flag=1
                    if flag==1:
                        return redirect('/account_profile')
                    else:
                        return render(request, 'main/login.html', {'error_message': 'Invalid Role'})

                else:
                    return render(request, 'main/login.html', {'error_message': 'Invalid Credentials'})

            else:
                return render(request, 'main/login.html', {'error_message': 'Invalid Credentials'})
        else:
            return render(request, 'main/login.html', {'error_message': 'Invalid Credentials'})
    return render(request, 'main/login.html',{'error_message': 'Valid Login'})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'main/login.html', context)


def student_profile(request):
    username=request.user.username
    username=str(username)
    student = Student.objects.get(webmail=username)
    return render(request, 'main/student.html',{'error_message': 'valid login', 'student': student})


def student_dept_detail(request):
    username=request.user.username
    username=str(username)
    student = Student.objects.get(webmail=username)
    faculty_dept = Faculty.objects.filter(dept=student.dept)
    stud_fac_status = StudFacStatus.objects.filter(student=student)
    return render(request,'main/student_dept_detail.html',{'error_message': 'valid login','student': student, 'faculty':faculty_dept, 'StudFacStatus': stud_fac_status})


def student_lab_detail(request):
    username = request.user.username
    username = str(username)
    student = Student.objects.get(webmail=username)
    labs = Lab.objects.all()
    stud_lab_status = StudLabStatus.objects.filter(student=student)
    return render(request, 'main/student_lab_detail.html', {'error_message': 'valid login', 'student': student, 'labs' : labs, 'StudLabStatus':stud_lab_status})


def account_profile(request):
    if request.method == "GET":
        username = request.user.username
        account = Account.objects.get(webmail=username)
        students = Student.objects.filter(hod_approval=True)
        return render(request, 'main/account.html',
                      {'error_message': 'valid login', 'students': students,
                       'account': account})
    elif request.method == "POST":
        username = request.user.username
        account = Account.objects.get(webmail=username)
        students = Student.objects.filter(hod_approval=True)
        for stud in students:
            if request.POST.get(stud.webmail, "") == 'on':
                stud.account_approval = True
                stud.save()
            else:
                stud.account_approval = False
                stud.save()
        return redirect('/account_profile',{'error_message': 'valid login', 'students': students,'account': account})


def assistant_registrar_profile(request):
    if request.method == "GET":
        username = request.user.username
        assistant_registrar= asstreg.objects.get(webmail=username)

main/templates/main/account.html
{% extends 'main/base.html' %}

{% block title %}
  Account | Home Page
{% endblock %}

{% block heading %}
    Students
{% endblock %}

{% block name %}
  {{ account.name  }}
{% endblock %}

{% block url %}
    {% url 'main:account_profile'%}
{% endblock %}

{% block form-action %}
    {% url 'main:account_profile'%}
{% endblock %}

{% block NotApproved %}
      {%for stud in students %}
          {% if stud.account_approval == False %}
                         <p align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="{{ stud.webmail }}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.roll }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.name }}</p>
          {% endif %}
      {% endfor %}
{% endblock %}
{% block Approved %}
      {%for stud in students %}
          {% if stud.account_approval == True %}
                         <p align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" checked name="{{ stud.webmail }}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.roll }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.name }}</p>
          {% endif %}
      {% endfor %}
{% endblock %}

main/templates/main/assistant_registrar.html
{% extends 'main/base.html' %}

{% block title %}
  Asst. Registrar | Home Page
{% endblock %}

{% block heading %}
    Students
{% endblock %}

{% block name %}
  {{ assistant_registrar.name  }}
{% endblock %}

{% block url %}
    {% url 'main:assistant_registrar_profile'%}
{% endblock %}

{% block form-action %}
    {% url 'main:assistant_registrar_profile'%}
{% endblock %}

{% block NotApproved %}
      {%for stud in students %}
          {% if stud.assistant_registrar_approval == False %}
                         <p align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="{{ stud.webmail }}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.roll }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.name }}</p>
          {% endif %}
      {% endfor %}
{% endblock %}
{% block Approved %}
      {%for stud in students %}
          {% if stud.assistant_registrar_approval == True %}
                         <p align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" checked name="{{ stud.webmail }}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.roll }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.name }}</p>
          {% endif %}
      {% endfor %}
{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}Faculty Catalog{% endblock %}</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }
    
    /* Remove the jumbotron's default bottom margin */
     .jumbotron {
      margin-bottom: 0;
    }
   
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }


    }
  </style>
</head>

<body>

<div class="container">
  <div class="container text-center">
    <img src="http://www.iitg.ernet.in/adas/images/iit_logo.jpg" alt="Mountain View" style="width:280px;height:200px;">
    <h1>No Dues Portal</h1>
    <p><h1><strong>Indian Institute of Technology, Guwahati<strong><h1></p>
  </div>
</div>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Logo</a> -->
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="{% block url %} url {% endblock %}"<span class="glyphicon glyphicon-home"></span>&nbsp;Home</a></li>
        <li><a href="{% url 'main:rules' %}" target="_blank"><span class="glyphicon glyphicon-info-sign"></span>&nbsp;Rules</a></li>
        <li><a href="{% url 'main:contact' %}" target="_blank"><span class="glyphicon glyphicon-earphone"></span>&nbsp;Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'main:logout_user' %}">{% block name %} Name {% endblock %}&nbsp;&nbsp;|&nbsp;&nbsp;<span class="glyphicon glyphicon-off"></span>&nbsp;&nbsp;Logout</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid text-center">
  <div class="row content">
  <div class="well">
        <h2>{% block heading %}Students{% endblock %}</h2>
  </div>
  <h4> <span class="glyphicon glyphicon-hand-right">&nbsp;</span>Check&nbsp;&nbsp;<span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;to approve No Dues </h4>
  <form class="form-horizontal" role="form" action="{% block form-action %}{% url 'main:faculty_profile'%}{% endblock %}" method="post" enctype="multipart/form-data">

    {% csrf_token %}
    <div class="col-sm-6 text-center">
        <h4>Not Approved</h4>
        <hr>
        <div class = "check-left">
{% block NotApproved %}
  
{% endblock %}
     </div>

    </div>
      <div class="col-sm-6 text-center">
        <h4>Approved</h4>

        <hr>
          <div class = "check-right">
{% block Approved %}
{% endblock %}

          </div>
      </div>

    </div>
    <br><br>
    <div class="col-sm-12">
      <button type="submit" onclick="return confirm('Are you sure?')" class="btn btn-success">Save changes</button>
    </div>
  </form>
</div>
<br><br>
<footer class="container-fluid text-center">
  <p><h4>&copy; <strong>2016 IIT Guwahati</strong></h><p> 
</footer>


</body>
</html>

main/templates/main/student_dept_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Student Department Full Detail</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }
    
    /* Remove the jumbotron's default bottom margin */
     .jumbotron {
      margin-bottom: 0;
    }
   
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }


    }
  </style>
</head>

<body>

<div class="container">
  <div class="container text-center">
    <img src="http://www.iitg.ernet.in/adas/images/iit_logo.jpg" alt="Mountain View" style="width:280px;height:200px;">
    <h1>No Dues Portal</h1>
    <p><h1><strong>Indian Institute of Technology, Guwahati<strong><h1></p>
  </div>
</div>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Logo</a> -->
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'main:student_profile' %}"><span class="glyphicon glyphicon-home"></span>&nbsp;Home</a></li>
        <li><a href="{% url 'main:rules' %}" target="_blank"><span class="glyphicon glyphicon-info-sign"></span>&nbsp;Rules</a></li>
        <li><a href="{% url 'main:contact' %}" target="_blank"><span class="glyphicon glyphicon-earphone"></span>&nbsp;Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'main:logout_user' %}"<span class="glyphicon glyphicon-user"></span>&nbsp;<STRONG>{{ student.name }}&nbsp;|&nbsp;<span class="glyphicon glyphicon-off"></span>&nbsp;Logout</STRONG></a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
    <div class="col-sm-12">
      <div class="well">
        <h4>Details :</h4>
        {%for i in StudFacStatus %}
            <p>
                {% if i.approval == True %}
                    <font color="green">{{ i.faculty.name }} &nbsp;:&nbsp; Approved</font>
                {%else%}
                    <font color="red">{{ i.faculty.name }} &nbsp;:&nbsp; Not Approved</font>
                {% endif %}
            </p>
          {% endfor %}
      </div>
    </div>

</div>
 

<div id="wrapper">
		<div id="header"></div>
		<div id="content"></div>
		<div id="footer"></div>
	</div>

<footer class="container-fluid text-center">
  <p><h4>&copy; <strong>2016 IIT Guwahati</strong></h><p> 
</footer>
</body>
</html>